name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "src/**"
  pull_request:
    branches:
    - main
    paths:
    - "src/**"
  
env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: src/blazorwasm-standalone-singleOrg
  # TESTING_DIRECTORY: src
  # GHPAGES_BASE: "/try-blazorwasm-standalone-singleOrg/"
  GHPAGES_BASE: "/"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v3
    - name: ✨ Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: 🚚 Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: 🛠️ Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: 📦 Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build -p:GHPages=true -p:GHPagesBase="${{ env.GHPAGES_BASE }}" --output publish
    - name: 🚀 Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: publish/wwwroot
        force_orphan: true
        # cname: wasm.trypage.tk
